ROOT:       "."
src:        "src/"
lib:        "lib/"
out:        "out/"
data_mount: "alluxio://master001:19998"

# SubDirectory Structure
src_main:   "src/main/"
src_data:   "src/data/"
out_stats:  "out/stats/"
out_counts: "out/counts/"
