ROOT:       "."
src:        "src/"
lib:        "lib/"
out:        "out/"
data_mount: "alluxio://master001:19998/"

# SubDirectory Structure
src_main:   "src/main/"
src_data:   "src/in_data/"
out_stats:  "out/data/stats/"
out_counts: "out/data/counts/"
out_log:    "out/log/"
