ROOT:       "./"
src:        "src/"
lib:        "lib/"
out:        "out/"
data_mount: "/home/lachlan/from_zurich/all-twitter-data/" #"alluxio://master001:19998/"

# SubDirectory Structure
src_main:   "src/main/"
src_data:   "src/in_data/"
out_chicago_stats:  "out/data/chicago/stats/"
out_chicago_counts: "out/data/chicago/counts/"
out_gnip_stats:  "out/data/gnip/stats/"
out_gnip_counts: "out/data/gnip/counts/"
out_gnip_vader: "out/data/vader/gnip/"
out_chicago_vader: "out/data/vader/chicago/"
out_log:    "out/log/"
out_lib:    "out/lib/"
out_list:   "out/list/"
