ROOT:       "./"
src:        "src/"
lib:        "lib/"
out:        "out/"
data_mount: "alluxio://master001:19998/"

# SubDirectory Structure
src_main:   "src/main/"
src_data:   "src/in_data/"
out_stats:  "out/data/chicago/daily-binary/stats/"
out_counts: "out/data/chicago/daily-binary/counts/"
out_gnip_stats:  "out/data/gnip/daily-binary/stats/"
out_gnip_counts: "out/data/gnip/daily-binary/counts/"
out_log:    "out/log/daily-binary/"
out_lib:    "out/lib/"
out_list:   "out/list/"
